FROM python:3.10.6

RUN apt-get update
RUN apt-get install -y libgl1-mesa-glx
RUN pip install --upgrade pip
RUN pip install opencv-python
RUN pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install pandas
RUN pip install ipython
RUN pip install psutil
RUN pip install pyyaml
RUN pip install tqdm
RUN pip install matplotlib
RUN pip install seaborn
RUN pip install fastapi[all]
RUN pip install uvicorn[standard]
RUN pip install importlib
RUN pip install ultralytics
RUN pip install dill
